"""Game code generator.

Template-based generation for MVP. Produces a Pygame game
from genre + prompt + difficulty. In the future, this will
integrate with genre_forge and optionally call an LLM.

All functions are synchronous (blocking) — call via asyncio.to_thread()
from the async worker.
"""

import json
import os
import shutil
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from app.config import settings


@dataclass
class GenerationResult:
    """Canonical output shape from game generation."""

    entrypoint: str = "main.py"
    files: dict[str, str] = field(default_factory=dict)
    summary: str = ""
    metadata: dict = field(default_factory=dict)


# --- Templates per genre ---

TEMPLATES: dict[str, str] = {
    "shooter": '''"""Space Shooter — generated by ArcadeForge"""
import pygame
import random
import sys

# --- Constants ---
WIDTH, HEIGHT = 800, 600
FPS = 60
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (255, 50, 50)
CYAN = (0, 255, 255)

pygame.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("{title}")
clock = pygame.time.Clock()
font = pygame.font.Font(None, 36)

# --- Player ---
player = pygame.Rect(WIDTH // 2 - 25, HEIGHT - 80, 50, 50)
player_speed = 6
bullets = []
bullet_speed = 8

# --- Enemies ---
enemies = []
enemy_speed = {enemy_speed}
spawn_timer = 0
spawn_interval = {spawn_interval}

# --- State ---
score = 0
game_over = False

def spawn_enemy():
    x = random.randint(20, WIDTH - 40)
    enemies.append(pygame.Rect(x, -40, 40, 40))

# --- Main Loop ---
running = True
while running:
    dt = clock.tick(FPS)

    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False
            if event.key == pygame.K_SPACE and not game_over:
                bullets.append(pygame.Rect(player.centerx - 3, player.top, 6, 12))

    if not game_over:
        keys = pygame.key.get_pressed()
        if keys[pygame.K_LEFT] and player.left > 0:
            player.x -= player_speed
        if keys[pygame.K_RIGHT] and player.right < WIDTH:
            player.x += player_speed

        # Update bullets
        for b in bullets[:]:
            b.y -= bullet_speed
            if b.bottom < 0:
                bullets.remove(b)

        # Spawn enemies
        spawn_timer += dt
        if spawn_timer >= spawn_interval:
            spawn_enemy()
            spawn_timer = 0

        # Update enemies
        for e in enemies[:]:
            e.y += enemy_speed
            if e.top > HEIGHT:
                enemies.remove(e)
                game_over = True

        # Collisions
        for b in bullets[:]:
            for e in enemies[:]:
                if b.colliderect(e):
                    bullets.remove(b)
                    enemies.remove(e)
                    score += 10
                    break

        if player.collidelist(enemies) != -1:
            game_over = True

    # --- Draw ---
    screen.fill(BLACK)
    pygame.draw.rect(screen, CYAN, player)
    for b in bullets:
        pygame.draw.rect(screen, WHITE, b)
    for e in enemies:
        pygame.draw.rect(screen, RED, e)

    score_text = font.render(f"Score: {{score}}", True, WHITE)
    screen.blit(score_text, (10, 10))

    if game_over:
        go_text = font.render("GAME OVER — Press ESC", True, RED)
        screen.blit(go_text, (WIDTH // 2 - go_text.get_width() // 2, HEIGHT // 2))

    pygame.display.flip()

pygame.quit()
sys.exit()
''',

    "puzzle": '''"""Puzzle Game — generated by ArcadeForge"""
import pygame
import random
import sys

WIDTH, HEIGHT = 600, 600
GRID_SIZE = {grid_size}
CELL = WIDTH // GRID_SIZE
FPS = 30
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
COLORS = [(255, 80, 80), (80, 255, 80), (80, 80, 255), (255, 255, 80)]

pygame.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("{title}")
clock = pygame.time.Clock()
font = pygame.font.Font(None, 36)

grid = [[random.randint(0, len(COLORS) - 1) for _ in range(GRID_SIZE)] for _ in range(GRID_SIZE)]
selected = None
score = 0
moves = 0

def draw_grid():
    for r in range(GRID_SIZE):
        for c in range(GRID_SIZE):
            color = COLORS[grid[r][c]]
            rect = pygame.Rect(c * CELL + 2, r * CELL + 2, CELL - 4, CELL - 4)
            pygame.draw.rect(screen, color, rect, border_radius=8)
            if selected == (r, c):
                pygame.draw.rect(screen, WHITE, rect, 3, border_radius=8)

def swap(r1, c1, r2, c2):
    grid[r1][c1], grid[r2][c2] = grid[r2][c2], grid[r1][c1]

running = True
while running:
    clock.tick(FPS)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            running = False
        if event.type == pygame.MOUSEBUTTONDOWN:
            mx, my = event.pos
            c, r = mx // CELL, my // CELL
            if 0 <= r < GRID_SIZE and 0 <= c < GRID_SIZE:
                if selected is None:
                    selected = (r, c)
                else:
                    sr, sc = selected
                    if abs(sr - r) + abs(sc - c) == 1:
                        swap(sr, sc, r, c)
                        moves += 1
                        score += 5
                    selected = None

    screen.fill(BLACK)
    draw_grid()
    info = font.render(f"Score: {{score}}  Moves: {{moves}}", True, WHITE)
    screen.blit(info, (10, HEIGHT - 40))
    pygame.display.flip()

pygame.quit()
sys.exit()
''',

    "sports": '''"""Sports Game (Pong) — generated by ArcadeForge"""
import pygame
import sys

WIDTH, HEIGHT = 800, 500
FPS = 60
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
PADDLE_W, PADDLE_H = 15, 80
BALL_SIZE = 12

pygame.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("{title}")
clock = pygame.time.Clock()
font = pygame.font.Font(None, 48)

left_paddle = pygame.Rect(30, HEIGHT // 2 - PADDLE_H // 2, PADDLE_W, PADDLE_H)
right_paddle = pygame.Rect(WIDTH - 45, HEIGHT // 2 - PADDLE_H // 2, PADDLE_W, PADDLE_H)
ball = pygame.Rect(WIDTH // 2 - BALL_SIZE // 2, HEIGHT // 2 - BALL_SIZE // 2, BALL_SIZE, BALL_SIZE)
ball_dx, ball_dy = {ball_speed}, {ball_speed}
paddle_speed = {paddle_speed}
score_left, score_right = 0, 0

def reset_ball():
    global ball_dx, ball_dy
    ball.center = (WIDTH // 2, HEIGHT // 2)
    ball_dx *= -1

running = True
while running:
    clock.tick(FPS)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN and event.key == pygame.K_ESCAPE:
            running = False

    keys = pygame.key.get_pressed()
    if keys[pygame.K_w] and left_paddle.top > 0:
        left_paddle.y -= paddle_speed
    if keys[pygame.K_s] and left_paddle.bottom < HEIGHT:
        left_paddle.y += paddle_speed
    if keys[pygame.K_UP] and right_paddle.top > 0:
        right_paddle.y -= paddle_speed
    if keys[pygame.K_DOWN] and right_paddle.bottom < HEIGHT:
        right_paddle.y += paddle_speed

    ball.x += ball_dx
    ball.y += ball_dy
    if ball.top <= 0 or ball.bottom >= HEIGHT:
        ball_dy *= -1
    if ball.colliderect(left_paddle) or ball.colliderect(right_paddle):
        ball_dx *= -1
    if ball.left <= 0:
        score_right += 1
        reset_ball()
    if ball.right >= WIDTH:
        score_left += 1
        reset_ball()

    screen.fill(BLACK)
    pygame.draw.rect(screen, WHITE, left_paddle)
    pygame.draw.rect(screen, WHITE, right_paddle)
    pygame.draw.ellipse(screen, WHITE, ball)
    pygame.draw.aaline(screen, WHITE, (WIDTH // 2, 0), (WIDTH // 2, HEIGHT))
    score_text = font.render(f"{{score_left}}  {{score_right}}", True, WHITE)
    screen.blit(score_text, (WIDTH // 2 - score_text.get_width() // 2, 20))
    pygame.display.flip()

pygame.quit()
sys.exit()
''',

    "platformer": '''"""Platformer — generated by ArcadeForge"""
import pygame
import sys

WIDTH, HEIGHT = 800, 500
FPS = 60
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
GREEN = (80, 200, 80)
BLUE = (80, 80, 255)
GRAVITY = 0.6
JUMP_POWER = -12

pygame.init()
screen = pygame.display.set_mode((WIDTH, HEIGHT))
pygame.display.set_caption("{title}")
clock = pygame.time.Clock()
font = pygame.font.Font(None, 36)

player = pygame.Rect(100, HEIGHT - 120, 32, 48)
vel_y = 0
on_ground = False
score = 0

platforms = [
    pygame.Rect(0, HEIGHT - 40, WIDTH, 40),
    pygame.Rect(200, 360, 150, 20),
    pygame.Rect(450, 280, 150, 20),
    pygame.Rect(150, 200, 150, 20),
    pygame.Rect(500, 140, 200, 20),
]

coins = [pygame.Rect(250, 330, 16, 16), pygame.Rect(500, 250, 16, 16), pygame.Rect(200, 170, 16, 16), pygame.Rect(580, 110, 16, 16)]

running = True
while running:
    clock.tick(FPS)
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            running = False
        if event.type == pygame.KEYDOWN:
            if event.key == pygame.K_ESCAPE:
                running = False
            if event.key == pygame.K_SPACE and on_ground:
                vel_y = JUMP_POWER
                on_ground = False

    keys = pygame.key.get_pressed()
    dx = 0
    if keys[pygame.K_LEFT]: dx = -{player_speed}
    if keys[pygame.K_RIGHT]: dx = {player_speed}
    player.x += dx
    player.x = max(0, min(WIDTH - player.width, player.x))

    vel_y += GRAVITY
    player.y += int(vel_y)

    on_ground = False
    for p in platforms:
        if player.colliderect(p) and vel_y >= 0:
            player.bottom = p.top
            vel_y = 0
            on_ground = True

    for c in coins[:]:
        if player.colliderect(c):
            coins.remove(c)
            score += 25

    screen.fill(BLACK)
    for p in platforms:
        pygame.draw.rect(screen, GREEN, p)
    for c in coins:
        pygame.draw.rect(screen, (255, 215, 0), c)
    pygame.draw.rect(screen, BLUE, player)
    score_text = font.render(f"Score: {{score}}", True, WHITE)
    screen.blit(score_text, (10, 10))
    pygame.display.flip()

pygame.quit()
sys.exit()
''',
}

# Difficulty presets per genre
DIFFICULTY_PARAMS: dict[str, dict[str, dict]] = {
    "shooter": {
        "easy": {"enemy_speed": 2, "spawn_interval": 1500},
        "medium": {"enemy_speed": 3, "spawn_interval": 1000},
        "hard": {"enemy_speed": 5, "spawn_interval": 600},
    },
    "puzzle": {
        "easy": {"grid_size": 4},
        "medium": {"grid_size": 6},
        "hard": {"grid_size": 8},
    },
    "sports": {
        "easy": {"ball_speed": 4, "paddle_speed": 5},
        "medium": {"ball_speed": 6, "paddle_speed": 6},
        "hard": {"ball_speed": 8, "paddle_speed": 7},
    },
    "platformer": {
        "easy": {"player_speed": 4},
        "medium": {"player_speed": 5},
        "hard": {"player_speed": 6},
    },
}


def generate_game(
    genre: str,
    title: str,
    prompt: str,
    difficulty: str = "medium",
) -> GenerationResult:
    """Generate game code from genre, title, prompt, and difficulty.

    This is a synchronous/blocking function.
    Call via asyncio.to_thread() from async code.
    """
    template = TEMPLATES.get(genre)
    if template is None:
        raise ValueError(f"No template for genre: {genre}")

    params = DIFFICULTY_PARAMS.get(genre, {}).get(difficulty, {})
    code = template.format(title=title, **params)

    blueprint = {
        "genre": genre,
        "title": title,
        "prompt": prompt,
        "difficulty": difficulty,
        "entrypoint": "main.py",
        "controls": _get_controls(genre),
    }

    return GenerationResult(
        entrypoint="main.py",
        files={"main.py": code},
        summary=f"{title} — a {genre} game ({difficulty} difficulty)",
        metadata=blueprint,
    )


async def generate_game_with_llm(
    provider: str,
    api_key: str,
    model: str,
    genre: str,
    title: str,
    prompt: str,
    difficulty: str = "medium",
) -> GenerationResult:
    """Generate game code using an LLM.

    Returns GenerationResult with the LLM-generated code.
    Raises RuntimeError if LLM call fails.
    """
    from app.games.llm_client import LLMConfig, generate_game_code

    config = LLMConfig(provider=provider, api_key=api_key, model=model)
    code = await generate_game_code(config, genre, title, prompt, difficulty)

    blueprint = {
        "genre": genre,
        "title": title,
        "prompt": prompt,
        "difficulty": difficulty,
        "entrypoint": "main.py",
        "controls": _get_controls(genre),
        "generated_by": f"llm:{provider}/{model}",
    }

    return GenerationResult(
        entrypoint="main.py",
        files={"main.py": code},
        summary=f"{title} — a {genre} game generated by {provider} ({difficulty} difficulty)",
        metadata=blueprint,
    )


def _get_controls(genre: str) -> dict:
    controls = {
        "shooter": {"move": "Arrow keys", "shoot": "Space", "quit": "ESC"},
        "puzzle": {"select": "Mouse click", "quit": "ESC"},
        "sports": {"left_paddle": "W/S", "right_paddle": "Up/Down", "quit": "ESC"},
        "platformer": {"move": "Arrow keys", "jump": "Space", "quit": "ESC"},
    }
    return controls.get(genre, {})


def save_to_workspace(
    user_id: str,
    game_id: str,
    version: int,
    result: GenerationResult,
) -> str:
    """Save generated files to the workspace directory atomically.

    Uses temp directory + os.replace for atomic move.
    Returns the workspace path.
    """
    base = Path(settings.storage_local_path) / "workspaces" / user_id / game_id / f"v{version}"

    # Write to temp first, then move atomically
    with tempfile.TemporaryDirectory(prefix="arcadeforge_gen_") as tmpdir:
        tmp_path = Path(tmpdir)

        for filename, content in result.files.items():
            filepath = tmp_path / filename
            filepath.parent.mkdir(parents=True, exist_ok=True)
            filepath.write_text(content, encoding="utf-8")

        # Write blueprint
        (tmp_path / "blueprint.json").write_text(
            json.dumps(result.metadata, indent=2),
            encoding="utf-8",
        )

        # Move to final location
        base.parent.mkdir(parents=True, exist_ok=True)
        if base.exists():
            shutil.rmtree(base)
        shutil.copytree(str(tmp_path), str(base))

    return str(base)
